apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: LoadBalancer  # Expose Adminer as a LoadBalancer service
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080  # Adminer container port
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  selector:
    matchLabels:
      app: adminer
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
