# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsrv
  template:
    metadata:
      labels:
        app: appsrv
    spec:
      initContainers:
        - name: sysctl-init
          image: busybox:latest
          command: ["sh", "-c", "sysctl -w fs.inotify.max_user_instances=512 fs.inotify.max_user_watches=524288"]
          securityContext:
            privileged: true
      containers:
        - name: appsrv
          image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-ecopoints/ecopoints-dotnet:latest
          # remove this when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: appsrv
spec:
  selector:
    app: appsrv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appsrv-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    # if the exposed path doesn't match backend path
    # INGRESS.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: if180123.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appsrv
                port:
                  number: 8080