apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment
  namespace: student-if200102
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: student-if200102
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "db"
            - name: POSTGRES_USER
              value: "app"
            - name: POSTGRES_PASSWORD
              value: "app"
          ports:
            - containerPort: 5432
