apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roles
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-nodes-role-binding
subjects:
  - kind: ServiceAccount
    name: if200102
    namespace: student-if200102
roleRef:
  kind: ClusterRole
  name: list-nodes-role
  apiGroup: rbac.authorization.k8s.io
