= Dokumentation
:toc:
:sectnums:
:icons: font

== OBD Compatibility

https://2324-4bhif-syp.github.io/2324-4bhif-syp-project-ecopoints/CarOBDDocumentation[Compatibility]

== Android App

* Development Environment: Android Studio Ladybug
* Target SDK: 34 (Android 14)

=== Features

* Auslesen von OBD2-Daten
* Live Anzeige von Fahrdaten
** Speichern der Daten während der Fahrt
* Ranking
* Profil

=== Communication with OBD

IMPORTANT: Ein OBD2-Adapter wird für das Auslesen der Daten benötigt.

Die Kommunikation mit dem OBD2-Adapter erfolgt über Bluetooth.
Der Adapter wird mit dem Smartphone verbunden und die App kann die Daten auslesen.

Wir benutzen die Bibliothek eltonvs / kotlin-obd-api für die Kommunikation mit dem OBD2-Adapter.

* https://github.com/eltonvs/kotlin-obd-api[github.com/eltonvs/kotlin-obd-api]

== Getting Started

=== Android App

1. In den Ordner der Android App navigieren

 ...cd ecopoints/

2. Im 'local.properties' muss der API Key für die Google Maps API eingetragen werden

 MAPS_API_KEY="YOUR_API_KEY"

3. Starten der App

 ./gradlew clean build --stacktrace

=== Backend

1. Navigate to the backend folder

 ...cd backend/

2. Start the quarkus application

    ./mvnw clean quarkus:dev

3. To run the tests for the application

    ./mvnw test

== Klassendiagramm
plantuml::plantuml/cld.puml[]

== Endpoints

Die kommunikation mit dem Backend erfolgt über REST-Endpoints.
Das Speichern von Trips und Fahrdaten erfolgt beim Beenden einer Fahrt.


==== Trips
Ein Trip setzt sich aus mehreren CarData-Objekten zusammen, die während der Fahrt laufend gesammelt werden.


image::images/trip-endpoints[]

[,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "distance": 0,
  "avg_speed": 0,
  "avg_engine_rotation": 0,
  "date": "2022-03-10",
  "rewarded_eco_points": 0
}
----

==== CarData
Ein CarData-Objekt enthält die Daten, die während der Fahrt gesammelt werden.

image::images/cardata-endpoints[]

[,json]
----
{
  "longitude": 0,
  "latitude": 0,
  "current_engine_rpm": 0,
  "current_velocity": 0,
  "throttle_position": 0,
  "engine_run_time": "string",
  "time_stamp": {
    "nanos": 0,
    "time": 0
  },
  "trip_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
----

==== User
Der User hat die Möglichkeit, sich einzuloggen, seine Fahrten zu tracken und seine Eco-Points zu sehen.

image::images/user-endpoints[]

== Deployment

* Oracle Cloud Server
** funktioniert nicht mehr
* Neue Deployment-Strategie to be done



