= Dokumentation
:toc:
:sectnums:

== Current-State - 11.10.2024

Android App:

* Manche OBD2-Daten werden ausgelesen und angezeigt
* Live Anzeige von Fahrdaten und GPS Daten (Broken)
** Live Fahrt auf Google Maps
** Speichern der Daten während der Fahrt
* Ranking Mockup
** Berechnung von Eco-Points für jede Fahrt anhand der Fahrdaten
** Anzeige des eigenen Rankings
** Anzeige anderer Nutzer (Ranking)
* Profil Mockup
** Anzeige der Eco-Points
* Anzeigen von Fahrten
** Mit Google Maps Integration
** Anzeigen der gefahrenen Strecke mittels Polyline
** Fahrdaten (Durchschnittsgeschwindigkeit, Durchschnittsverbrauch, etc.)

=== Problems

* OBD2-Daten werden nicht immer korrekt ausgelesen
* Google Maps API für die Kartenanzeige hatte major changes und ist nicht mehr kompatibel
* Das Backend läuft auf keinem Server und ist nicht erreichbar
* Berechnung der Eco-Points ist noch nicht implementiert

=== Task

* OBD2-Daten korrekt auslesen
* Google Maps API migrieren
* Backend auf einem Server deployen
** CI/CD Pipeline für ein automatisches Deployment

=== Goals

Ecopoints app soll es ermöglichen, Fahrdaten auszulesen und anhand dieser Daten Eco-Points zu berechnen.
Diese Eco-Points sollen in einem Ranking angezeigt werden.
Die App soll auch die Möglichkeit bieten, die gefahrenen Strecken auf einer Karte anzuzeigen.

== Getting Started

=== Android App

1. In den Ordner der Android App navigieren

 ...cd ecopoints/

2. Starten der App

    ./gradlew clean build --stacktrace

=== Backend

1. Navigate to the backend folder

 ...cd backend/

2. Start the quarkus application

    ./mvnw clean quarkus:dev

3. To run the tests for the application

    ./mvnw test

== Android App

Target SDK: 34 (Android 14)

=== Features

* Auslesen von OBD2-Daten
* Live Anzeige von Fahrdaten
* Anzeige von Fahrten
** Mit Karte - Google Maps API
* Ranking
* Profil

== API

image::img/EcoPoints-Diagram[]

=== Communication with OBD

IMPORTANT: Ein OBD2-Adapter wird für das Auslesen der Daten benötigt.

Die Kommunikation mit dem OBD2-Adapter erfolgt über Bluetooth. Der Adapter wird mit dem Smartphone verbunden und die App kann die Daten auslesen.

Wir benutzen die Bibliothek eltonvs / kotlin-obd-api für die Kommunikation mit dem OBD2-Adapter.

* https://github.com/eltonvs/kotlin-obd-api[github.com/eltonvs/kotlin-obd-api]

=== Endpoints

Die kommunikation mit dem Backend erfolgt über REST-Endpoints.
Das Speichern von Trips und Fahrdaten erfolgt beim Beenden einer Fahrt.


==== Trips


image::img/trip-endpoints[]

[,json]
----
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "distance": 0,
  "avg_speed": 0,
  "avg_engine_rotation": 0,
  "date": "2022-03-10",
  "rewarded_eco_points": 0
}
----

==== CarData

image::img/cardata-endpoints[]

[,json]
----
{
  "longitude": 0,
  "latitude": 0,
  "current_engine_rpm": 0,
  "current_velocity": 0,
  "throttle_position": 0,
  "engine_run_time": "string",
  "time_stamp": {
    "nanos": 0,
    "time": 0
  },
  "trip_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
----

==== User

image::img/user-endpoints[]

== Deployment



