POST http://localhost:8080/api/carData
Content-Type: application/json

{
  "trip_id": "457c247e-0723-4170-80c4-826762de4743",
  "longitude": 45.123456,
  "latitude": 34.567890,
  "current_engine_rpm": 3000.0,
  "current_velocity": 60.0,
  "throttle_position": 75.0,
  "engine_run_time": "14:30:15",
  "time_stamp": "2023-11-08T13:45:00.000Z"
}

###

POST http://localhost:8080/api/carData
Content-Type: application/json

{
	"trip_id": "457c247e-0723-4170-80c4-826762de4743",
	"longitude":10.0,
	"latitude":20.0,
	"current_engine_rpm":3000.0,
	"current_velocity":60.0,
	"throttle_position":50.0,
	"engine_run_time":"10:00",
	"time_stamp":"Nov 28, 2023, 9:53:53 AM"
}

###

POST http://localhost:8080/api/trip
Content-Type: application/json

{
  "id": "457c247e-0723-4170-80c4-826762de4743",
  "distance": 100.0,
  "avg_speed": 44.0,
  "avg_engine_rotation": 3000.0,
  "date": "2023-11-28T08:49:06Z",
  "rewarded_eco_points": 10.0
}

###

POST http://localhost:8080/api/user
Content-Type: application/json

{
  "user_name": "John",
  "password": "John123",
  "eco_points": 133.00
}

###

GET http://localhost:8080/api/carData/1
Accept: application/json

###

GET http://localhost:8080/api/carData
Accept: application/json

###

PUT http://localhost:8080/api/carData/1
Content-Type: application/json

{
  "id": 1,
  "trip_id": "5d59e169-94a4-4bf7-8a8e-6a52a1d85f0f",
  "longitude": 24.12,
  "latitude": 33.98,
  "current_engine_rpm": 3000.0,
  "current_velocity": 60.0,
  "throttle_position": 75.0,
  "engine_run_time": "14:30:15",
  "time_stamp": "2023-11-08T13:45:00.000Z"
}

###

DELETE http://localhost:8080/api/carData/1
Accept: application/json

###


